server:
  port: 8081
  servlet:
    context-path: /api

spring:
  rabbitmq:
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}

app:
  read-only: false
  rabbit:
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}
